model: "Phi-3.6-mini-instruct"
model_path: "model"
save_dir: "mount/<run_id>/save_dir"
finetune_dataset: "mount/<run_id>/training_data/cursor_keyboard_train.json"
max_input_size: 512
init_prompt: "Control cursor and keyboard actions. Respond with ACTION: commands for mouse movements, clicks, scrolling, and keyboard inputs."
number_of_virtual_tokens: 128
learning_rate: !!float 5e-05
early_stopping_patience: 8
epochs: 3
evaluation_strategy: "steps"
eval_steps: 16
save_steps: 32
seed: 42
finetune_train_nsamples: 50
finetune_test_nsamples: 20
finetune_train_batch_size: 2
finetune_test_batch_size: 2
