adam_beta1: !!float 0.9
adam_beta2: !!float 0.95
adam_epsilon: !!float 1E-08
early_stopping_patience: 10
epochs: 5
eval_accumulation_steps: null
eval_delay: 0
eval_steps: 16
evaluation_strategy: "steps"
save_dir: "mount/<run_id>/save_dir"
finetune_dataset: "mount/<run_id>/training_data/cursor_keyboard_train.json"
finetune_test_batch_size: 4
finetune_test_nsamples: 20
finetune_test_seqlen: 512
finetune_train_batch_size: 2
finetune_train_nsamples: 50
finetune_train_seqlen: 512
gradient_accumulation_steps: 1
gradient_checkpointing: false
learning_rate: !!float 0.0001
lora_dropout: !!float 0.05
lr_scheduler_type: "cosine_with_warmup"
max_grad_norm: 1.0
model: "Phi-3.6-mini-instruct"
model_path: "model"
num_training_steps: null
num_warmup_steps: 50
save_steps: 32
seed: 42
weight_decay: 0.01
